### ISSUE TITLE
An issue running the models_demo notebook

### ISSUE THREAD

**Issue by aslansd** [ecker-lab/sensorium_2023#2]
Hi all,

When I am running the 7th cell-code of the models_demo notebook, I encounter the following error:

```
File D:\Sensorium2023\sensorium_2023-main\sensorium\models\make_model.py:131, in <dictcomp>(.0)
    125     in_shapes_dict = {
    126         k: get_module_output(core, v)[1:] for k, v in session_shape_dict_2d.items()
    127     }
    129 if deeplake_ds:
    130     mean_activity_dict = {
--> 131         k: next(iter(dataloaders[k]))["responses"].mean(0).mean(-1)
    132         for k in dataloaders.keys()
    133     }
    134 else:
    135     mean_activity_dict = {
    136         k: next(iter(dataloaders[k]))[1].mean(0).mean(-1)
    137         for k in dataloaders.keys()
    138     }

TypeError: tuple indices must be integers or slices, not str
```

I was wondering if you could be helpful. By the way, my python is 3.10.9. As a first guess, I think I need to change the "responses" to a numerical index.

**Comment by pollytur** [comment]
@aslansd based on your path, I guess you are running the code over windows. Have you changed this [line](https://github.com/ecker-lab/sensorium_2023/blob/main/sensorium/datasets/mouse_video_loaders.py#L148) toward `dataset_name = path.split("\")[-2]` ?

**Comment by pollytur** [comment]
@Nicola17 your issue is different. I am sorry, there is a typo in the demo notebook and it was recently fixed (thanks @Mvystrcilova ). When one defines a data loaders, the amount of frames should be more than 50. 

<img width="688" alt="image" src="https://github.com/ecker-lab/sensorium_2023/assets/49938348/5475f38b-82e2-4df4-91ea-c63b33e5cce6">

PS. If for some reasons you want to train with less frames, then you could either comment out [this assertion](https://github.com/ecker-lab/sensorium_2023/blob/main/sensorium/utility/scores.py#L47) or reduce the [skip](https://github.com/ecker-lab/sensorium_2023/blob/main/sensorium/utility/scores.py#L10C48-L10C55) parameter, however, for the actual evaluation we would skip exactly 50 frames (this is why there is an assertion there).
