### ISSUE TITLE
model_demo.ipynb submission won't work

### ISSUE THREAD

**Issue by davidchd** [ecker-lab/sensorium_2023#7]
The generated submission file appears to be broken when I tried to run **model_demo.ipynb**. I used the first model mentioned in the notebook, and I barely changed anything. After some examination of the generated file, I figured that each cell in prediction is an array of size (7800+, 10) instead of the required size for submission (xxxx, 250). [This](https://github.com/ecker-lab/sensorium_2023/assets/15072424/8a926c64-9dd1-48d5-9c2c-b80606b9e363) is a screenshot of the error message when I submit my file. I'm using the Main [new] track. 

Edit: In addition to the issue above, I wonder if there is an api that we can use to submit our result. Uploading through web is painful, especially for people who train models on a remote server. One would have to download the data file from the remote host and upload locally. It can take an hour to just uploading a single submission.

**Comment by pollytur** [comment]
I am very sorry for the long reply.

The issue is the `data_loaders` variable was not updated from the training regime (there is a frames parameter there, which cuts random N frames, where N=60 is the tutorial). To make a prediction for the whole sequence  you can set `to_cut=False` (`True` by default) during creating a dataloader like (`data_loaders = mouse_video_loader(... to_cut=False)`  (`frames` parameter would be ignored in this case and `generate_submission` should cut the redundant frames).

Hope this helps!
